### ISSUE TITLE
【技术咨询】同步写入标签时被卡住

### ISSUE THREAD

**Issue by tobe718** [huskar-t/opcda#14]
## 背景
使用konimarti/opc实现的一个程序，在对一个设备厂家提供OPCDA服务执行写入操作不时会出现卡住的情况。
采集程序和OPCDA服务都在同一电脑上

## 问题
我想咨询下，本地COM方式是不是就是DLL调用，如果服务端不响应那就永远无法返回？

**Comment by huskar-t** [comment]
即使在同一台机器上也有可能出现这种情况，没有手段去设置超时，有两种绕过的方法
1. 使用异步接口
2. 使用 go 协程

**Comment by tobe718** [comment]
> 即使在同一台机器上也有可能出现这种情况，没有手段去设置超时，有两种绕过的方法
> 
> 1. 使用异步接口
> 2. 使用 go 协程

所以这其实是厂家的opc服务没做好吧？

**Comment by huskar-t** [comment]
> > 即使在同一台机器上也有可能出现这种情况，没有手段去设置超时，有两种绕过的方法
> > 
> > 1. 使用异步接口
> > 2. 使用 go 协程
> 
> 所以这其实是厂家的opc服务没做好吧？

有可能
