### ISSUE TITLE
panic: Invalid class string

### ISSUE THREAD

**Issue by DevMinions** [huskar-t/opcda#6]
连接除了本机地址以外的ip地址就会报这个错误，我发现是因为clsid, err := windows.GUIDFromString(progID)返回的是{00000000-0000-0000-0000-000000000000}，为什么会这样呢？是我的环境没装对吗还是其它什么原因？

**Comment by huskar-t** [comment]
@yuminuo 连接其他 ip 需要提前配置好 dcom，你配置了吗

**Comment by yuminuo** [comment]
配置了 我使用konimarti/opc这个包可以正常连接

**Comment by DevMinions** [comment]
@huskar-t 配置了 我使用konimarti/opc这个包可以正常连接

**Comment by huskar-t** [comment]
连接远程的处理确实存在问题，我会尽快进行修复

**Comment by huskar-t** [comment]
通过 GetOPCServers 能看到远程机器上的 ProgID 和 ClsStr 吗

**Comment by DevMinions** [comment]
@huskar-t 能看到 这个是正常的

**Comment by huskar-t** [comment]
@yuminuo I made some modifications in the `fix/remote` branch, please verify whether the problem is solved

**Comment by DevMinions** [comment]
@huskar-t Thank you for your attention to this matter. I have examined the changes in the fix/remote branch, and I am delighted to report that the issue has been successfully resolved. Your solution is much appreciated.

**Comment by huskar-t** [comment]
fixed in v0.2.1
