### ISSUE TITLE
Class not registered

### ISSUE THREAD

**Issue by eleking328** [huskar-t/opcda#8]
Hello, I am currently testing your project and encountered a panic error. Could you please confirm if additional system configurations are required to run the test program? Thank you.

**Comment by huskar-t** [comment]
@eleking328 Please post your error message

**Comment by eleking328** [comment]
> @eleking328 Please post your error message

err msg is "connect to opc server failed: Class not registered"，when the exe connect to the opcwatchit plug that is used on emerson dcs system.

**Comment by huskar-t** [comment]
@eleking328 maybe you need to install OPC Core Components  https://opcfoundation.org/developer-tools/samples-and-tools-classic/core-components/

**Comment by eleking328** [comment]
> @eleking328 maybe you need to install OPC Core Components https://opcfoundation.org/developer-tools/samples-and-tools-classic/core-components/

thank you ,i will try. I'm puzzled as to why Konimarti/OPC can connect to Emerson's plugins and read data successfully, yet there seems to be an incompatibility. Could it be due to differences in the underlying implementation?

**Comment by huskar-t** [comment]
> > @eleking328 maybe you need to install OPC Core Components https://opcfoundation.org/developer-tools/samples-and-tools-classic/core-components/
> 
> thank you ,i will try. I'm puzzled as to why Konimarti/OPC can connect to Emerson's plugins and read data successfully, yet there seems to be an incompatibility. Could it be due to differences in the underlying implementation?

If Konimarti/OPC can connect, it may not be a problem of opc core not being installed. It should be that the opc protocol version of Emerson's plugins is low. I have tested kepware and MatrikonOPC Simulation and there are no problems. Maybe I can test this plugin. Can you give me a document address of the software you use?

**Comment by eleking328** [comment]
> > > @eleking328 maybe you need to install OPC Core Components https://opcfoundation.org/developer-tools/samples-and-tools-classic/core-components/
> > 
> > 
> > thank you ,i will try. I'm puzzled as to why Konimarti/OPC can connect to Emerson's plugins and read data successfully, yet there seems to be an incompatibility. Could it be due to differences in the underlying implementation?
> 
> If Konimarti/OPC can connect, it may not be a problem of opc core not being installed. It should be that the opc protocol version of Emerson's plugins is low. I have tested kepware and MatrikonOPC Simulation and there are no problems. Maybe I can test this plugin. Can you give me a document address of the software you use?

Sorry, the Emerson plugin is designed to work exclusively with its corresponding device and cannot be used separately for verification purposes.

**Comment by huskar-t** [comment]
@eleking328 Can you try to connect to the opc da server using MatrikonOPC Explorer? If you can connect, check the interfaces support in properties. https://www.matrikonopc.com/products/opc-desktop-tools/opc-explorer.aspx
![image](https://github.com/huskar-t/opcda/assets/26872926/33b29200-95b6-425b-addc-a4917089a2d7)
![image](https://github.com/huskar-t/opcda/assets/26872926/b6b69469-bb54-4ff5-bb30-12aec6129de5)

**Comment by huskar-t** [comment]
@eleking328 I tried some opc da servers in a clean windows system and found that some opc servers didn't have core components installed. But for fix #6, I made a hack fix to get clsid using OpcServerList api, but OpcServerList relies on core components. I will fix this issue in two weeks. You can try version v0.2.0 and give feedback

**Comment by huskar-t** [comment]
@eleking328 Or you can install `OPC Core Components Redistributable (x64) 3.00.108.msi`

**Comment by eleking328** [comment]
> OPC Core Components Redistributable (x64) 3.00.108.msi

Thank you. I'll give it a try and I look forward to your update.

**Comment by huskar-t** [comment]
@eleking328 Can you test it using the commit `github.com/huskar-t/opcda v0.2.2-0.20240614043657-5cb0e67808a5`?

**Comment by eleking328** [comment]
> @eleking328 Can you test it using the commit `github.com/huskar-t/opcda v0.2.2-0.20240614043657-5cb0e67808a5`?

Sorry for the oversight, I forgot to respond to your message. Despite my attempts, I encountered the same error. Additionally, I have installed the OPC Core Components Redistributable (x64) 3.00.108.msi

**Comment by huskar-t** [comment]
Caused by irregular use of CoCreateInstanceEx interface.
fixed: #9

**Comment by huskar-t** [comment]
fixed: v0.3.0
